name: 5GTM-Interhack_BCN_2026
description: <a id="readme-top"></a>
ports: []
bricks:
- arduino:web_ui: {}
- arduino:dbstorage_tsstore: {}
- arduino:video_object_detection:
    model: ei-model-991247-1
icon: 😀
